fix: repositories update & add more checks

diff --git a/scripts/updatearch b/scripts/updatearch
--- a/scripts/updatearch
+++ b/scripts/updatearch
@@ -103,8 +103,12 @@ if [[ -d "$REPODIR" ]]; then
 
     if [[ -d "$REPODIR/$REPO" ]]; then
       echo -e "\e[0;1;90m:: Updating \e[0;1;3;94m$entry\e[0m"
+      cd "$REPODIR/$REPO" >&/dev/null || echo -e "\e[90m:: \e[1;91mERROR\e[0;90m - Cannot cd to \e[1;3;94m$REPODIR/$REPO\e[0;90m\e[0m"
+
       [[ -d "$REPODIR/$REPO/.git" ]] && git pull
-      [[ -f "$REPODIR/$REPO/build.zig" ]] && zig build
+      [[ -f "$REPODIR/$REPO/build.zig" && "$REPO" != *"template"* ]] && zig build
+
+      cd - >&/dev/null || echo -e "\e[90m:: \e[1;91mERROR\e[0;90m - Cannot cd back\e[0m"
       echo
     fi
   done
